//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod payroll_entry_bulk;
pub mod salary_slip_bulk;
pub mod salary_slip_line_bulk;
pub mod salary_structure_bulk;
pub mod salary_component_bulk;

pub use payroll_entry_bulk::PayrollEntryBulkService;
pub use salary_slip_bulk::SalarySlipBulkService;
pub use salary_slip_line_bulk::SalarySlipLineBulkService;
pub use salary_structure_bulk::SalaryStructureBulkService;
pub use salary_component_bulk::SalaryComponentBulkService;

// <<< CUSTOM
// END CUSTOM
