//! Bulk operations for PayrollEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePayrollEntryDto;
use crate::application::service::PayrollEntryService;
use crate::domain::entity::PayrollEntry;

/// Bulk operation handler for PayrollEntry entities.
///
/// Wraps `PayrollEntryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PayrollEntryBulkService = GenericBulkService<PayrollEntry, CreatePayrollEntryDto, PayrollEntryService>;

// <<< CUSTOM
// END CUSTOM
