//! Bulk operations for SalarySlipLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSalarySlipLineDto;
use crate::application::service::SalarySlipLineService;
use crate::domain::entity::SalarySlipLine;

/// Bulk operation handler for SalarySlipLine entities.
///
/// Wraps `SalarySlipLineService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SalarySlipLineBulkService = GenericBulkService<SalarySlipLine, CreateSalarySlipLineDto, SalarySlipLineService>;

// <<< CUSTOM
// END CUSTOM
