//! Bulk operations for SalaryStructure entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSalaryStructureDto;
use crate::application::service::SalaryStructureService;
use crate::domain::entity::SalaryStructure;

/// Bulk operation handler for SalaryStructure entities.
///
/// Wraps `SalaryStructureService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SalaryStructureBulkService = GenericBulkService<SalaryStructure, CreateSalaryStructureDto, SalaryStructureService>;

// <<< CUSTOM
// END CUSTOM
