//! Bulk operations for SalarySlip entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSalarySlipDto;
use crate::application::service::SalarySlipService;
use crate::domain::entity::SalarySlip;

/// Bulk operation handler for SalarySlip entities.
///
/// Wraps `SalarySlipService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SalarySlipBulkService = GenericBulkService<SalarySlip, CreateSalarySlipDto, SalarySlipService>;

// <<< CUSTOM
// END CUSTOM
