//! Bulk operations for SalaryComponent entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSalaryComponentDto;
use crate::application::service::SalaryComponentService;
use crate::domain::entity::SalaryComponent;

/// Bulk operation handler for SalaryComponent entities.
///
/// Wraps `SalaryComponentService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SalaryComponentBulkService = GenericBulkService<SalaryComponent, CreateSalaryComponentDto, SalaryComponentService>;

// <<< CUSTOM
// END CUSTOM
