//! CompensationChange DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::CompensationChange;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CompensationChangeType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new CompensationChange
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCompensationChangeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(alias = "change_type")]
    pub change_type: CompensationChangeType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "new_amount")]
    pub new_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "effective_date")]
    pub effective_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reference_id")]
    pub reference_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a CompensationChange
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCompensationChangeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(alias = "change_type")]
    pub change_type: CompensationChangeType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "new_amount")]
    pub new_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "effective_date")]
    pub effective_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reference_id")]
    pub reference_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a CompensationChange
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCompensationChangeDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "change_type")]
    pub change_type: Option<CompensationChangeType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "new_amount")]
    pub new_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "effective_date")]
    pub effective_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reference_id")]
    pub reference_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
}

impl PatchCompensationChangeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.change_type.is_some() || self.new_amount.is_some() || self.effective_date.is_some() || self.reference_id.is_some() || self.note.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for CompensationChange entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompensationChangeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub change_type: CompensationChangeType,
    pub new_amount: Option<Decimal>,
    pub effective_date: Option<NaiveDate>,
    pub reference_id: Option<Uuid>,
    pub note: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for CompensationChange entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompensationChangeListResponseDto {
    /// List of items
    pub items: Vec<CompensationChangeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CompensationChangeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CompensationChangeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CompensationChangeSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub change_type: CompensationChangeType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<CompensationChange> for CompensationChangeResponseDto {
    fn from(entity: CompensationChange) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            change_type: entity.change_type,
            new_amount: entity.new_amount,
            effective_date: entity.effective_date,
            reference_id: entity.reference_id,
            note: entity.note,
            metadata: entity.metadata,
        }
    }
}

impl From<CompensationChange> for CompensationChangeSummaryDto {
    fn from(entity: CompensationChange) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            change_type: entity.change_type,
            created_at,
        }
    }
}

impl From<CreateCompensationChangeDto> for CompensationChange {
    fn from(dto: CreateCompensationChangeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            change_type: dto.change_type,
            new_amount: dto.new_amount,
            effective_date: dto.effective_date,
            reference_id: dto.reference_id,
            note: dto.note,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&CompensationChange> for CompensationChangeResponseDto {
    fn from(entity: &CompensationChange) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            change_type: entity.change_type.clone(),
            new_amount: entity.new_amount.clone(),
            effective_date: entity.effective_date.clone(),
            reference_id: entity.reference_id.clone(),
            note: entity.note.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCompensationChangeDto> for CompensationChange {
    fn from_create_dto(dto: CreateCompensationChangeDto) -> backbone_core::ServiceResult<Self> {
        Ok(CompensationChange::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCompensationChangeDto> for CompensationChange {
    fn apply_update(mut self, dto: UpdateCompensationChangeDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.change_type = dto.change_type;
        self.new_amount = dto.new_amount;
        self.effective_date = dto.effective_date;
        self.reference_id = dto.reference_id;
        self.note = dto.note;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to CompensationChange here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

