//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod payroll_entry_specification;
pub mod salary_slip_specification;
pub mod salary_slip_line_specification;
pub mod salary_structure_specification;
pub mod salary_component_specification;

// <<< CUSTOM
// END CUSTOM
