//! Specifications for SalarySlip aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Entity-specific predicate structs implementing `backbone_core::Specification`.
//! Combinators (AND/OR/NOT) are available via the trait methods — no duplication.

use backbone_core::Specification;
use crate::domain::entity::SalarySlip;

pub use backbone_core::{AndSpecification, OrSpecification, NotSpecification};

// ─── Entity-specific predicates ──────────────────────────────────────────────
//
// Add entity-specific predicate structs below.
// Each predicate implements `Specification<SalarySlip>` and can be combined
// using `.and()`, `.or()`, `.not()` from the trait.
//
// Example:
//   let spec = ActiveSpec.and(VerifiedSpec);
//   if spec.is_satisfied_by(&entity) { ... }

// <<< CUSTOM
// Add predicate structs here. Example:
//
// pub struct ActiveSalarySlipSpec;
// impl Specification<SalarySlip> for ActiveSalarySlipSpec {
//     fn is_satisfied_by(&self, e: &SalarySlip) -> bool {
//         // e.is_active
//         todo!()
//     }
// }
// END CUSTOM