//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod payroll_entry_domain_policy;
pub mod salary_slip_domain_policy;
pub mod salary_slip_line_domain_policy;
pub mod salary_structure_domain_policy;
pub mod salary_component_domain_policy;

pub use payroll_entry_domain_policy::PayrollEntryDomainPolicy;
pub use salary_slip_domain_policy::SalarySlipDomainPolicy;
pub use salary_slip_line_domain_policy::SalarySlipLineDomainPolicy;
pub use salary_structure_domain_policy::SalaryStructureDomainPolicy;
pub use salary_component_domain_policy::SalaryComponentDomainPolicy;

// <<< CUSTOM
// END CUSTOM
