//! Domain policy for PayrollEntry aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::PayrollEntry;

/// Domain policy for PayrollEntry — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<PayrollEntry>` in the `// <<< CUSTOM` zone.
pub type PayrollEntryDomainPolicy = PermitAllPolicy<PayrollEntry>;

// <<< CUSTOM
// END CUSTOM
