//! Domain policy for SalaryStructure aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::SalaryStructure;

/// Domain policy for SalaryStructure — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<SalaryStructure>` in the `// <<< CUSTOM` zone.
pub type SalaryStructureDomainPolicy = PermitAllPolicy<SalaryStructure>;

// <<< CUSTOM
// END CUSTOM
