//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod payroll_entry_service;
pub mod salary_slip_service;
pub mod salary_slip_line_service;
pub mod salary_structure_service;
pub mod salary_component_service;

// <<< CUSTOM
pub mod payroll_gl;
pub mod payroll_events;
pub mod payroll_write_service;
// END CUSTOM

pub use payroll_entry_service::PayrollEntryService;
pub use salary_slip_service::SalarySlipService;
pub use salary_slip_line_service::SalarySlipLineService;
pub use salary_structure_service::SalaryStructureService;
pub use salary_component_service::SalaryComponentService;
// <<< CUSTOM
pub use payroll_gl::{
    AccountingPostEnvelope, GlPostAck, GlPostLine, GlPostRejected, GlPostSink,
};
pub use payroll_events::{
    LoggingSink, PayrollEvent, PayrollEventSink, PayrollPayable, PayrollPosted,
};
pub use payroll_write_service::{
    NewComponent, NewPayrollEntry, NewSalarySlip, NewStructure, PayrollError, PayrollWriteService,
    PostOutcome, StatutoryLine,
};
// END CUSTOM