//! Application service for PayrollEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `payroll_entry_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePayrollEntryDto, UpdatePayrollEntryDto};
use crate::domain::entity::PayrollEntry;
use crate::infrastructure::persistence::PayrollEntryRepository;

/// Application service for PayrollEntry entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `payroll_entry_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PayrollEntryServiceCustom {
///     inner: Arc<PayrollEntryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PayrollEntryService = GenericCrudService<
    PayrollEntry,
    CreatePayrollEntryDto,
    UpdatePayrollEntryDto,
    PayrollEntryRepository,
>;

// <<< CUSTOM
// END CUSTOM
