//! Application service for SalarySlip entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `salary_slip_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSalarySlipDto, UpdateSalarySlipDto};
use crate::domain::entity::SalarySlip;
use crate::infrastructure::persistence::SalarySlipRepository;

/// Application service for SalarySlip entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `salary_slip_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SalarySlipServiceCustom {
///     inner: Arc<SalarySlipService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SalarySlipService = GenericCrudService<
    SalarySlip,
    CreateSalarySlipDto,
    UpdateSalarySlipDto,
    SalarySlipRepository,
>;

// <<< CUSTOM
// END CUSTOM
