//! Application service for SalarySlipLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `salary_slip_line_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSalarySlipLineDto, UpdateSalarySlipLineDto};
use crate::domain::entity::SalarySlipLine;
use crate::infrastructure::persistence::SalarySlipLineRepository;

/// Application service for SalarySlipLine entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `salary_slip_line_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SalarySlipLineServiceCustom {
///     inner: Arc<SalarySlipLineService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SalarySlipLineService = GenericCrudService<
    SalarySlipLine,
    CreateSalarySlipLineDto,
    UpdateSalarySlipLineDto,
    SalarySlipLineRepository,
>;

// <<< CUSTOM
// END CUSTOM
