//! Application service for SalaryStructure entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `salary_structure_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSalaryStructureDto, UpdateSalaryStructureDto};
use crate::domain::entity::SalaryStructure;
use crate::infrastructure::persistence::SalaryStructureRepository;

/// Application service for SalaryStructure entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `salary_structure_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SalaryStructureServiceCustom {
///     inner: Arc<SalaryStructureService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SalaryStructureService = GenericCrudService<
    SalaryStructure,
    CreateSalaryStructureDto,
    UpdateSalaryStructureDto,
    SalaryStructureRepository,
>;

// <<< CUSTOM
// END CUSTOM
