-- CompensationChange Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payroll.compensation_changes table.
-- Customize this file to add your initial data.

-- INSERT INTO payroll.compensation_changes (
--     id,
--     company_id,
--     employee_id,
--     change_type,
--     new_amount,
--     effective_date,
--     reference_id,
--     note,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO payroll.compensation_changes (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

