-- PayrollEntry Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payroll.payroll_entries table.
-- Customize this file to add your initial data.

-- INSERT INTO payroll.payroll_entries (
--     id,
--     company_id,
--     period_year,
--     period_month,
--     posting_date,
--     status,
--     salary_expense_account_id,
--     salary_payable_account_id,
--     total_gross,
--     total_deductions,
--     total_net,
--     journal_id,
--     accounting_post_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO payroll.payroll_entries (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

