-- SalarySlipLine Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payroll.salary_slip_lines table.
-- Customize this file to add your initial data.

-- INSERT INTO payroll.salary_slip_lines (
--     id,
--     salary_slip_id,
--     name,
--     component_type,
--     is_statutory,
--     amount,
--     gl_account_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO payroll.salary_slip_lines (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

