-- SalarySlip Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the payroll.salary_slips table.
-- Customize this file to add your initial data.

-- INSERT INTO payroll.salary_slips (
--     id,
--     payroll_entry_id,
--     company_id,
--     employee_id,
--     structure_id,
--     working_days,
--     unpaid_days,
--     gross_pay,
--     total_deductions,
--     net_pay,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO payroll.salary_slips (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

