-- Migration: Create salary_structures table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS payroll;

CREATE TABLE IF NOT EXISTS payroll.salary_structures (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_salary_structures_company_id_is_active ON payroll.salary_structures (company_id, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_salary_structures_metadata_gin ON payroll.salary_structures USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_salary_structures_metadata_deleted_at ON payroll.salary_structures ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_salary_structures_metadata_created_at ON payroll.salary_structures ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_salary_structures_metadata_updated_at ON payroll.salary_structures ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payroll.salary_structures_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS salary_structures_insert_audit ON payroll.salary_structures;
CREATE TRIGGER salary_structures_insert_audit BEFORE INSERT ON payroll.salary_structures
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_structures_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS salary_structures_update_audit ON payroll.salary_structures;
CREATE TRIGGER salary_structures_update_audit BEFORE UPDATE ON payroll.salary_structures
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_structures_audit_timestamp();
