-- Company RLS fence for payroll module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for payroll.payroll_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payroll.payroll_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll.payroll_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payroll_entries_company_isolation ON payroll.payroll_entries;
CREATE POLICY payroll_entries_company_isolation ON payroll.payroll_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payroll.salary_slips
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payroll.salary_slips ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll.salary_slips FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS salary_slips_company_isolation ON payroll.salary_slips;
CREATE POLICY salary_slips_company_isolation ON payroll.salary_slips
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payroll.salary_structures
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payroll.salary_structures ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll.salary_structures FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS salary_structures_company_isolation ON payroll.salary_structures;
CREATE POLICY salary_structures_company_isolation ON payroll.salary_structures
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

