-- Revert the ADR-0014 strict company fence for payroll module (Wave 1 P0 sweep).
-- Generated by metaphor-schema.
DROP POLICY IF EXISTS compensation_changes_company_isolation ON payroll.compensation_changes;
ALTER TABLE payroll.compensation_changes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE payroll.compensation_changes DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payroll_entries_company_isolation ON payroll.payroll_entries;
ALTER TABLE payroll.payroll_entries NO FORCE ROW LEVEL SECURITY;
ALTER TABLE payroll.payroll_entries DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS salary_components_company_isolation ON payroll.salary_components;
ALTER TABLE payroll.salary_components NO FORCE ROW LEVEL SECURITY;
ALTER TABLE payroll.salary_components DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS salary_slip_lines_company_isolation ON payroll.salary_slip_lines;
ALTER TABLE payroll.salary_slip_lines NO FORCE ROW LEVEL SECURITY;
ALTER TABLE payroll.salary_slip_lines DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS salary_slips_company_isolation ON payroll.salary_slips;
ALTER TABLE payroll.salary_slips NO FORCE ROW LEVEL SECURITY;
ALTER TABLE payroll.salary_slips DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS salary_structures_company_isolation ON payroll.salary_structures;
ALTER TABLE payroll.salary_structures NO FORCE ROW LEVEL SECURITY;
ALTER TABLE payroll.salary_structures DISABLE ROW LEVEL SECURITY;
