-- Audit Triggers Migration for payroll module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: PayrollEntry (payroll.payroll_entries)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION payroll.payroll_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS payroll_entries_insert_audit ON payroll.payroll_entries;
CREATE TRIGGER payroll_entries_insert_audit BEFORE INSERT ON payroll.payroll_entries
    FOR EACH ROW EXECUTE FUNCTION payroll.payroll_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS payroll_entries_update_audit ON payroll.payroll_entries;
CREATE TRIGGER payroll_entries_update_audit BEFORE UPDATE ON payroll.payroll_entries
    FOR EACH ROW EXECUTE FUNCTION payroll.payroll_entries_audit_timestamp();

-- ==============================================================================
-- Table: SalarySlip (payroll.salary_slips)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION payroll.salary_slips_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS salary_slips_insert_audit ON payroll.salary_slips;
CREATE TRIGGER salary_slips_insert_audit BEFORE INSERT ON payroll.salary_slips
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_slips_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS salary_slips_update_audit ON payroll.salary_slips;
CREATE TRIGGER salary_slips_update_audit BEFORE UPDATE ON payroll.salary_slips
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_slips_audit_timestamp();

-- ==============================================================================
-- Table: SalarySlipLine (payroll.salary_slip_lines)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION payroll.salary_slip_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS salary_slip_lines_insert_audit ON payroll.salary_slip_lines;
CREATE TRIGGER salary_slip_lines_insert_audit BEFORE INSERT ON payroll.salary_slip_lines
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_slip_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS salary_slip_lines_update_audit ON payroll.salary_slip_lines;
CREATE TRIGGER salary_slip_lines_update_audit BEFORE UPDATE ON payroll.salary_slip_lines
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_slip_lines_audit_timestamp();

-- ==============================================================================
-- Table: SalaryStructure (payroll.salary_structures)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION payroll.salary_structures_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS salary_structures_insert_audit ON payroll.salary_structures;
CREATE TRIGGER salary_structures_insert_audit BEFORE INSERT ON payroll.salary_structures
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_structures_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS salary_structures_update_audit ON payroll.salary_structures;
CREATE TRIGGER salary_structures_update_audit BEFORE UPDATE ON payroll.salary_structures
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_structures_audit_timestamp();

-- ==============================================================================
-- Table: SalaryComponent (payroll.salary_components)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION payroll.salary_components_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS salary_components_insert_audit ON payroll.salary_components;
CREATE TRIGGER salary_components_insert_audit BEFORE INSERT ON payroll.salary_components
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_components_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS salary_components_update_audit ON payroll.salary_components;
CREATE TRIGGER salary_components_update_audit BEFORE UPDATE ON payroll.salary_components
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_components_audit_timestamp();

