-- Migration: Create payroll_entries table
-- Generated by metaphor-schema

-- Create payroll_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payroll_status') THEN
        CREATE TYPE payroll_status AS ENUM ('draft', 'processed', 'posted', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS payroll;

CREATE TABLE IF NOT EXISTS payroll.payroll_entries (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    period_year INTEGER NOT NULL,
    period_month INTEGER NOT NULL,
    posting_date TIMESTAMPTZ,
    status payroll_status NOT NULL DEFAULT 'draft',
    salary_expense_account_id UUID,
    salary_payable_account_id UUID,
    total_gross NUMERIC NOT NULL DEFAULT 0,
    total_deductions NUMERIC NOT NULL DEFAULT 0,
    total_net NUMERIC NOT NULL DEFAULT 0,
    journal_id UUID,
    accounting_post_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_payroll_entries_company_id_period_year_period_month ON payroll.payroll_entries (company_id, period_year, period_month);

CREATE INDEX IF NOT EXISTS idx_payroll_entries_company_id_status ON payroll.payroll_entries (company_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_payroll_entries_metadata_gin ON payroll.payroll_entries USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_payroll_entries_metadata_deleted_at ON payroll.payroll_entries ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_payroll_entries_metadata_created_at ON payroll.payroll_entries ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_payroll_entries_metadata_updated_at ON payroll.payroll_entries ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payroll.payroll_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS payroll_entries_insert_audit ON payroll.payroll_entries;
CREATE TRIGGER payroll_entries_insert_audit BEFORE INSERT ON payroll.payroll_entries
    FOR EACH ROW EXECUTE FUNCTION payroll.payroll_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS payroll_entries_update_audit ON payroll.payroll_entries;
CREATE TRIGGER payroll_entries_update_audit BEFORE UPDATE ON payroll.payroll_entries
    FOR EACH ROW EXECUTE FUNCTION payroll.payroll_entries_audit_timestamp();
