-- Enum types for payroll module
-- Generated by metaphor-schema

-- Create payroll_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payroll_status') THEN
        CREATE TYPE payroll_status AS ENUM ('draft', 'processed', 'posted', 'cancelled');
    END IF;
END
$$;

-- Create component_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'component_type') THEN
        CREATE TYPE component_type AS ENUM ('earning', 'deduction');
    END IF;
END
$$;

