-- Migration: Create salary_slips table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS payroll;

CREATE TABLE IF NOT EXISTS payroll.salary_slips (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    payroll_entry_id UUID NOT NULL,
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    structure_id UUID,
    working_days NUMERIC(6, 2) NOT NULL DEFAULT 0 CHECK (working_days >= 0),
    unpaid_days NUMERIC(6, 2) NOT NULL DEFAULT 0 CHECK (unpaid_days >= 0),
    gross_pay NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (gross_pay >= 0),
    total_deductions NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (total_deductions >= 0),
    net_pay NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (net_pay >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_salary_slips_payroll_entry_id_employee_id ON payroll.salary_slips (payroll_entry_id, employee_id);

CREATE INDEX IF NOT EXISTS idx_salary_slips_company_id_employee_id ON payroll.salary_slips (company_id, employee_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_salary_slips_metadata_gin ON payroll.salary_slips USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_salary_slips_metadata_deleted_at ON payroll.salary_slips ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_salary_slips_metadata_created_at ON payroll.salary_slips ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_salary_slips_metadata_updated_at ON payroll.salary_slips ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payroll.salary_slips_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS salary_slips_insert_audit ON payroll.salary_slips;
CREATE TRIGGER salary_slips_insert_audit BEFORE INSERT ON payroll.salary_slips
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_slips_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS salary_slips_update_audit ON payroll.salary_slips;
CREATE TRIGGER salary_slips_update_audit BEFORE UPDATE ON payroll.salary_slips
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_slips_audit_timestamp();
