-- Migration: Create salary_components table
-- Generated by metaphor-schema

-- Create component_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'component_type') THEN
        CREATE TYPE component_type AS ENUM ('earning', 'deduction');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS payroll;

CREATE TABLE IF NOT EXISTS payroll.salary_components (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    structure_id UUID NOT NULL,
    name TEXT NOT NULL,
    component_type component_type NOT NULL DEFAULT 'earning',
    amount NUMERIC NOT NULL DEFAULT 0,
    gl_account_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_salary_components_structure_id ON payroll.salary_components (structure_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_salary_components_metadata_gin ON payroll.salary_components USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_salary_components_metadata_deleted_at ON payroll.salary_components ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_salary_components_metadata_created_at ON payroll.salary_components ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_salary_components_metadata_updated_at ON payroll.salary_components ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION payroll.salary_components_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS salary_components_insert_audit ON payroll.salary_components;
CREATE TRIGGER salary_components_insert_audit BEFORE INSERT ON payroll.salary_components
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_components_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS salary_components_update_audit ON payroll.salary_components;
CREATE TRIGGER salary_components_update_audit BEFORE UPDATE ON payroll.salary_components
    FOR EACH ROW EXECUTE FUNCTION payroll.salary_components_audit_timestamp();
