-- Company fence posture for payroll module (ADR-0014: strict)
-- Generated by metaphor-schema. Every entity here carries company_id and is fenced
-- strict: a session sees only rows whose company_id equals the request-scoped
-- company (`set_config('app.company_id', <uuid>, true)`); an unset var sees zero
-- rows (fail-closed). These tables shipped company_id without a policy since the
-- pre-ADR-0014 policy cleanup; this migration installs the declared fence
-- (Wave 1 P0 sweep, 2026-08-16). Requires the app to connect as a non-superuser
-- role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for payroll.compensation_changes
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payroll.compensation_changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll.compensation_changes FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS compensation_changes_company_isolation ON payroll.compensation_changes;
CREATE POLICY compensation_changes_company_isolation ON payroll.compensation_changes
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payroll.payroll_entries
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payroll.payroll_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll.payroll_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS payroll_entries_company_isolation ON payroll.payroll_entries;
CREATE POLICY payroll_entries_company_isolation ON payroll.payroll_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payroll.salary_components
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payroll.salary_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll.salary_components FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS salary_components_company_isolation ON payroll.salary_components;
CREATE POLICY salary_components_company_isolation ON payroll.salary_components
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payroll.salary_slip_lines
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payroll.salary_slip_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll.salary_slip_lines FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS salary_slip_lines_company_isolation ON payroll.salary_slip_lines;
CREATE POLICY salary_slip_lines_company_isolation ON payroll.salary_slip_lines
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payroll.salary_slips
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payroll.salary_slips ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll.salary_slips FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS salary_slips_company_isolation ON payroll.salary_slips;
CREATE POLICY salary_slips_company_isolation ON payroll.salary_slips
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for payroll.salary_structures
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE payroll.salary_structures ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll.salary_structures FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS salary_structures_company_isolation ON payroll.salary_structures;
CREATE POLICY salary_structures_company_isolation ON payroll.salary_structures
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);
