//! Domain events for CompensationChange entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CompensationChange;

/// Domain events for CompensationChange — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CompensationChange>)` variant.
pub type CompensationChangeEvent = CrudEvent<CompensationChange>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CompensationChange events.
pub type CompensationChangeEventPublisher = Arc<dyn CrudEventPublisher<CompensationChange> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCompensationChangeEventPublisher = NoOpCrudEventPublisher<CompensationChange>;
