//! Event handler trait for CompensationChange events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CompensationChangeEvent;

/// Event handler for CompensationChange events.
/// Implement this trait to react to CompensationChange lifecycle events.
pub trait CompensationChangeEventHandler: EventHandler<CompensationChangeEvent> {}
