//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod payroll_entry_events;
pub mod payroll_entry_event_handlers;
pub mod salary_slip_events;
pub mod salary_slip_event_handlers;
pub mod salary_slip_line_events;
pub mod salary_slip_line_event_handlers;
pub mod salary_structure_events;
pub mod salary_structure_event_handlers;
pub mod salary_component_events;
pub mod salary_component_event_handlers;

pub use payroll_entry_events::{PayrollEntryEvent, PayrollEntryEventPublisher, NoopPayrollEntryEventPublisher};
pub use payroll_entry_event_handlers::PayrollEntryEventHandler;
pub use salary_slip_events::{SalarySlipEvent, SalarySlipEventPublisher, NoopSalarySlipEventPublisher};
pub use salary_slip_event_handlers::SalarySlipEventHandler;
pub use salary_slip_line_events::{SalarySlipLineEvent, SalarySlipLineEventPublisher, NoopSalarySlipLineEventPublisher};
pub use salary_slip_line_event_handlers::SalarySlipLineEventHandler;
pub use salary_structure_events::{SalaryStructureEvent, SalaryStructureEventPublisher, NoopSalaryStructureEventPublisher};
pub use salary_structure_event_handlers::SalaryStructureEventHandler;
pub use salary_component_events::{SalaryComponentEvent, SalaryComponentEventPublisher, NoopSalaryComponentEventPublisher};
pub use salary_component_event_handlers::SalaryComponentEventHandler;

// <<< CUSTOM
// END CUSTOM
