//! Domain events for PayrollEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PayrollEntry;

/// Domain events for PayrollEntry — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PayrollEntry>)` variant.
pub type PayrollEntryEvent = CrudEvent<PayrollEntry>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PayrollEntry events.
pub type PayrollEntryEventPublisher = Arc<dyn CrudEventPublisher<PayrollEntry> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPayrollEntryEventPublisher = NoOpCrudEventPublisher<PayrollEntry>;
