//! Event handler trait for PayrollEntry events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PayrollEntryEvent;

/// Event handler for PayrollEntry events.
/// Implement this trait to react to PayrollEntry lifecycle events.
pub trait PayrollEntryEventHandler: EventHandler<PayrollEntryEvent> {}
