//! Event handler trait for SalarySlip events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SalarySlipEvent;

/// Event handler for SalarySlip events.
/// Implement this trait to react to SalarySlip lifecycle events.
pub trait SalarySlipEventHandler: EventHandler<SalarySlipEvent> {}
