//! Event handler trait for SalaryComponent events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SalaryComponentEvent;

/// Event handler for SalaryComponent events.
/// Implement this trait to react to SalaryComponent lifecycle events.
pub trait SalaryComponentEventHandler: EventHandler<SalaryComponentEvent> {}
