//! Event handler trait for SalarySlipLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SalarySlipLineEvent;

/// Event handler for SalarySlipLine events.
/// Implement this trait to react to SalarySlipLine lifecycle events.
pub trait SalarySlipLineEventHandler: EventHandler<SalarySlipLineEvent> {}
