//! Domain events for SalaryComponent entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SalaryComponent;

/// Domain events for SalaryComponent — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SalaryComponent>)` variant.
pub type SalaryComponentEvent = CrudEvent<SalaryComponent>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SalaryComponent events.
pub type SalaryComponentEventPublisher = Arc<dyn CrudEventPublisher<SalaryComponent> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSalaryComponentEventPublisher = NoOpCrudEventPublisher<SalaryComponent>;
