//! Domain events for SalaryStructure entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SalaryStructure;

/// Domain events for SalaryStructure — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SalaryStructure>)` variant.
pub type SalaryStructureEvent = CrudEvent<SalaryStructure>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SalaryStructure events.
pub type SalaryStructureEventPublisher = Arc<dyn CrudEventPublisher<SalaryStructure> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSalaryStructureEventPublisher = NoOpCrudEventPublisher<SalaryStructure>;
