//! Domain events for SalarySlipLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SalarySlipLine;

/// Domain events for SalarySlipLine — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SalarySlipLine>)` variant.
pub type SalarySlipLineEvent = CrudEvent<SalarySlipLine>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SalarySlipLine events.
pub type SalarySlipLineEventPublisher = Arc<dyn CrudEventPublisher<SalarySlipLine> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSalarySlipLineEventPublisher = NoOpCrudEventPublisher<SalarySlipLine>;
