//! Domain events for SalarySlip entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SalarySlip;

/// Domain events for SalarySlip — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SalarySlip>)` variant.
pub type SalarySlipEvent = CrudEvent<SalarySlip>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SalarySlip events.
pub type SalarySlipEventPublisher = Arc<dyn CrudEventPublisher<SalarySlip> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSalarySlipEventPublisher = NoOpCrudEventPublisher<SalarySlip>;
