//! Event handler trait for SalaryStructure events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SalaryStructureEvent;

/// Event handler for SalaryStructure events.
/// Implement this trait to react to SalaryStructure lifecycle events.
pub trait SalaryStructureEventHandler: EventHandler<SalaryStructureEvent> {}
