//! Event subscriber type aliases for Payroll module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::PayrollEntryEvent;
use crate::domain::event::SalarySlipEvent;
use crate::domain::event::SalarySlipLineEvent;
use crate::domain::event::SalaryStructureEvent;
use crate::domain::event::SalaryComponentEvent;

/// Subscriber for PayrollEntry events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PayrollEntryEventSubscriber = GenericEventSubscriber<PayrollEntryEvent>;

/// Subscriber for SalarySlip events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SalarySlipEventSubscriber = GenericEventSubscriber<SalarySlipEvent>;

/// Subscriber for SalarySlipLine events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SalarySlipLineEventSubscriber = GenericEventSubscriber<SalarySlipLineEvent>;

/// Subscriber for SalaryStructure events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SalaryStructureEventSubscriber = GenericEventSubscriber<SalaryStructureEvent>;

/// Subscriber for SalaryComponent events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SalaryComponentEventSubscriber = GenericEventSubscriber<SalaryComponentEvent>;

// <<< CUSTOM
// END CUSTOM
