//! CompensationChange seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial CompensationChange data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// COMPENSATIONCHANGE SEEDER
// ============================================================================

/// Seeder for compensation_change
pub struct SeedCompensationChangeSeeder;

impl SeedCompensationChangeSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCompensationChangeSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCompensationChangeSeeder {
    fn name(&self) -> &'static str {
        "SeedCompensationChangeSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if payroll.compensation_changes table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM payroll.compensation_changes")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/compensation_change_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM payroll.compensation_changes")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

