//! SalarySlip seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial SalarySlip data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SALARYSLIP SEEDER
// ============================================================================

/// Seeder for salary_slip
pub struct SeedSalarySlipSeeder;

impl SeedSalarySlipSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSalarySlipSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSalarySlipSeeder {
    fn name(&self) -> &'static str {
        "SeedSalarySlipSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if payroll.salary_slips table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM payroll.salary_slips")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/salary_slip_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM payroll.salary_slips")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

