//! SalarySlipLine seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial SalarySlipLine data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SALARYSLIPLINE SEEDER
// ============================================================================

/// Seeder for salary_slip_line
pub struct SeedSalarySlipLineSeeder;

impl SeedSalarySlipLineSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSalarySlipLineSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSalarySlipLineSeeder {
    fn name(&self) -> &'static str {
        "SeedSalarySlipLineSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if payroll.salary_slip_lines table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM payroll.salary_slip_lines")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/salary_slip_line_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM payroll.salary_slip_lines")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

