//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod payroll_entry_repository;
pub mod salary_slip_repository;
pub mod salary_slip_line_repository;
pub mod salary_structure_repository;
pub mod salary_component_repository;

// Re-exports
pub use payroll_entry_repository::{
    PayrollEntryRepository,
    PayrollEntryPaginationParams,
    PayrollEntryPaginatedResult,
    PayrollEntryFilter,
};
pub use salary_slip_repository::{
    SalarySlipRepository,
    SalarySlipPaginationParams,
    SalarySlipPaginatedResult,
    SalarySlipFilter,
};
pub use salary_slip_line_repository::{
    SalarySlipLineRepository,
    SalarySlipLinePaginationParams,
    SalarySlipLinePaginatedResult,
    SalarySlipLineFilter,
};
pub use salary_structure_repository::{
    SalaryStructureRepository,
    SalaryStructurePaginationParams,
    SalaryStructurePaginatedResult,
    SalaryStructureFilter,
};
pub use salary_component_repository::{
    SalaryComponentRepository,
    SalaryComponentPaginationParams,
    SalaryComponentPaginatedResult,
    SalaryComponentFilter,
};
