//! Repository trait for SalarySlipLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SalarySlipLine aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{SalarySlipLine, ComponentType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalarySlipLinePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SalarySlipLinePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SalarySlipLinePaginatedResult {
    pub data: Vec<SalarySlipLine>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalarySlipLineFilter {
    pub salary_slip_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub component_type: Option<ComponentType>,
    pub is_statutory: Option<bool>,
    pub gl_account_id: Option<Uuid>,
}

impl SalarySlipLineFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.salary_slip_id.is_some() || self.company_id.is_some() || self.name.is_some() || self.component_type.is_some() || self.is_statutory.is_some() || self.gl_account_id.is_some()
    }
}

/// Repository trait for SalarySlipLine aggregate
///
/// This trait defines the persistence contract for SalarySlipLine entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SalarySlipLineRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new salary_slip_line entity
    async fn save(&self, entity: &SalarySlipLine) -> Result<SalarySlipLine>;

    /// Find salary_slip_line by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SalarySlipLine>>;

    /// Find all salary_slip_line entities
    async fn find_all(&self) -> Result<Vec<SalarySlipLine>>;

    /// Update salary_slip_line by ID
    async fn update(&self, id: &str, entity: &SalarySlipLine) -> Result<Option<SalarySlipLine>>;

    /// Delete salary_slip_line by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List salary_slip_line with pagination
    async fn list(&self, params: SalarySlipLinePaginationParams) -> Result<SalarySlipLinePaginatedResult>;

    /// List salary_slip_line with pagination and filters
    async fn list_with_filters(&self, params: SalarySlipLinePaginationParams, filters: SalarySlipLineFilter) -> Result<SalarySlipLinePaginatedResult>;

    /// Count all salary_slip_line entities
    async fn count(&self) -> Result<u64>;

    /// Count salary_slip_line entities matching filters
    async fn count_with_filters(&self, filters: SalarySlipLineFilter) -> Result<u64>;

    /// Check if salary_slip_line exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete salary_slip_line by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted salary_slip_line by ID
    async fn restore(&self, id: &str) -> Result<Option<SalarySlipLine>>;

    /// List soft-deleted salary_slip_line entities
    async fn list_deleted(&self, params: SalarySlipLinePaginationParams) -> Result<SalarySlipLinePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save salary_slip_line entities
    async fn bulk_save(&self, entities: &[SalarySlipLine]) -> Result<Vec<SalarySlipLine>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
