//! Repository trait for SalarySlip aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SalarySlip aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SalarySlip;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalarySlipPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SalarySlipPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SalarySlipPaginatedResult {
    pub data: Vec<SalarySlip>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalarySlipFilter {
    pub payroll_entry_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub structure_id: Option<Uuid>,
}

impl SalarySlipFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.payroll_entry_id.is_some() || self.company_id.is_some() || self.employee_id.is_some() || self.structure_id.is_some()
    }
}

/// Repository trait for SalarySlip aggregate
///
/// This trait defines the persistence contract for SalarySlip entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SalarySlipRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new salary_slip entity
    async fn save(&self, entity: &SalarySlip) -> Result<SalarySlip>;

    /// Find salary_slip by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SalarySlip>>;

    /// Find all salary_slip entities
    async fn find_all(&self) -> Result<Vec<SalarySlip>>;

    /// Update salary_slip by ID
    async fn update(&self, id: &str, entity: &SalarySlip) -> Result<Option<SalarySlip>>;

    /// Delete salary_slip by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List salary_slip with pagination
    async fn list(&self, params: SalarySlipPaginationParams) -> Result<SalarySlipPaginatedResult>;

    /// List salary_slip with pagination and filters
    async fn list_with_filters(&self, params: SalarySlipPaginationParams, filters: SalarySlipFilter) -> Result<SalarySlipPaginatedResult>;

    /// Count all salary_slip entities
    async fn count(&self) -> Result<u64>;

    /// Count salary_slip entities matching filters
    async fn count_with_filters(&self, filters: SalarySlipFilter) -> Result<u64>;

    /// Check if salary_slip exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete salary_slip by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted salary_slip by ID
    async fn restore(&self, id: &str) -> Result<Option<SalarySlip>>;

    /// List soft-deleted salary_slip entities
    async fn list_deleted(&self, params: SalarySlipPaginationParams) -> Result<SalarySlipPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save salary_slip entities
    async fn bulk_save(&self, entities: &[SalarySlip]) -> Result<Vec<SalarySlip>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
