//! Repository trait for SalaryStructure aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SalaryStructure aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SalaryStructure;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalaryStructurePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SalaryStructurePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SalaryStructurePaginatedResult {
    pub data: Vec<SalaryStructure>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalaryStructureFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub is_active: Option<bool>,
}

impl SalaryStructureFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for SalaryStructure aggregate
///
/// This trait defines the persistence contract for SalaryStructure entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SalaryStructureRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new salary_structure entity
    async fn save(&self, entity: &SalaryStructure) -> Result<SalaryStructure>;

    /// Find salary_structure by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SalaryStructure>>;

    /// Find all salary_structure entities
    async fn find_all(&self) -> Result<Vec<SalaryStructure>>;

    /// Update salary_structure by ID
    async fn update(&self, id: &str, entity: &SalaryStructure) -> Result<Option<SalaryStructure>>;

    /// Delete salary_structure by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List salary_structure with pagination
    async fn list(&self, params: SalaryStructurePaginationParams) -> Result<SalaryStructurePaginatedResult>;

    /// List salary_structure with pagination and filters
    async fn list_with_filters(&self, params: SalaryStructurePaginationParams, filters: SalaryStructureFilter) -> Result<SalaryStructurePaginatedResult>;

    /// Count all salary_structure entities
    async fn count(&self) -> Result<u64>;

    /// Count salary_structure entities matching filters
    async fn count_with_filters(&self, filters: SalaryStructureFilter) -> Result<u64>;

    /// Check if salary_structure exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete salary_structure by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted salary_structure by ID
    async fn restore(&self, id: &str) -> Result<Option<SalaryStructure>>;

    /// List soft-deleted salary_structure entities
    async fn list_deleted(&self, params: SalaryStructurePaginationParams) -> Result<SalaryStructurePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save salary_structure entities
    async fn bulk_save(&self, entities: &[SalaryStructure]) -> Result<Vec<SalaryStructure>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
