//! Repository for CompensationChange entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<CompensationChange, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::CompensationChange;

/// Table name for CompensationChange entities
pub const TABLE_NAME: &str = "payroll.compensation_changes";

/// Repository for CompensationChange entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CompensationChangeRepository(
    backbone_orm::GenericCrudRepository<CompensationChange, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CompensationChangeRepository {
    type Target = backbone_orm::GenericCrudRepository<CompensationChange, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CompensationChangeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CompensationChangeRepository, CompensationChange, soft_delete);
