//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod payroll_entry_repository;
mod salary_slip_repository;
mod salary_slip_line_repository;
mod salary_structure_repository;
mod salary_component_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use payroll_entry_repository::PayrollEntryRepository;
pub use salary_slip_repository::SalarySlipRepository;
pub use salary_slip_line_repository::SalarySlipLineRepository;
pub use salary_structure_repository::SalaryStructureRepository;
pub use salary_component_repository::SalaryComponentRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
