//! Repository for PayrollEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PayrollEntry, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PayrollEntry;

/// Table name for PayrollEntry entities
pub const TABLE_NAME: &str = "payroll.payroll_entries";

/// Repository for PayrollEntry entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PayrollEntryRepository(
    backbone_orm::GenericCrudRepository<PayrollEntry, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PayrollEntryRepository {
    type Target = backbone_orm::GenericCrudRepository<PayrollEntry, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PayrollEntryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PayrollEntryRepository, PayrollEntry, soft_delete);
