//! Repository for PayrollEntry entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written PayrollEntry SQL — the run lifecycle and the transition gate that makes
//! a run post to the GL at most once (4-layer rule: services orchestrate, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PayrollEntry, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PayrollEntry;

/// Table name for PayrollEntry entities
pub const TABLE_NAME: &str = "payroll.payroll_entries";

/// Repository for PayrollEntry entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PayrollEntryRepository(
    backbone_orm::GenericCrudRepository<PayrollEntry, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PayrollEntryRepository {
    type Target = backbone_orm::GenericCrudRepository<PayrollEntry, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PayrollEntryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a run open writes. Mirrors the raw column shape, not the `PayrollEntry` entity: the
/// insert hard-codes `draft` status and seeds all three totals at 0, so none of those are parameters.
pub struct NewPayrollEntryRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub period_year: i32,
    pub period_month: i32,
    pub salary_expense_account_id: Uuid,
    pub salary_payable_account_id: Uuid,
}

/// A live run's company + lifecycle state — what the slip path reads before it writes.
pub struct RunScopeRow {
    pub company_id: Uuid,
    pub status: String,
}

/// What the GL post path reads before it builds the journal. The account columns are nullable in the
/// schema, so they come back as `Option` for the caller to reject; `journal_id`/`accounting_post_id`
/// are Some only once posted, which is what makes a re-post return the original journal.
pub struct RunPostingRow {
    pub company_id: Uuid,
    pub status: String,
    pub salary_expense_account_id: Option<Uuid>,
    pub salary_payable_account_id: Option<Uuid>,
    pub total_gross: Decimal,
    pub total_deductions: Decimal,
    pub total_net: Decimal,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
}

/// Hand-written PayrollEntry SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl PayrollEntryRepository {
    /// Open a payroll run for a company/period, as a draft with zeroed totals.
    ///
    /// A write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company is
    /// on the DTO, and that scope is what satisfies the INSERT's WITH CHECK.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to turn
    /// a second run on the same (company, year, month) into a domain error.
    pub async fn insert_entry(
        &self,
        pool: &PgPool,
        e: &NewPayrollEntryRow,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO payroll.payroll_entries
                     (id, company_id, period_year, period_month, status, salary_expense_account_id,
                      salary_payable_account_id, total_gross, total_deductions, total_net)
                   VALUES ($1,$2,$3,$4,'draft'::payroll_status,$5,$6,0,0,0)"#,
            )
            .bind(e.id).bind(e.company_id).bind(e.period_year).bind(e.period_month)
            .bind(e.salary_expense_account_id).bind(e.salary_payable_account_id),
        )
        .await?;
        Ok(())
    }

    /// Read a live run's company + status — the slip path's lookup. `Ok(None)` = not found in scope.
    ///
    /// ID-only: no company argument to scope from up front. `fetch_optional_row_scoped` means it rides a
    /// connection carrying the caller's `app.company_id`, so another company's run simply isn't found.
    /// The company comes back on the row so the caller can bind its own tx to it.
    pub async fn find_scope_by_id(
        &self,
        pool: &PgPool,
        run_id: Uuid,
    ) -> Result<Option<RunScopeRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, status::text AS status FROM payroll.payroll_entries
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(run_id),
        )
        .await?;
        Ok(row.map(|r| RunScopeRow { company_id: r.get("company_id"), status: r.get("status") }))
    }

    /// Record the rolled-up totals and move `draft → processed`. Returns rows affected: 0 = not draft.
    ///
    /// ID-only: no company argument — `execute_scoped` rides the request-dedicated connection's
    /// `app.company_id`. An event-driven caller must wrap this in
    /// `with_company_scope(Some(event.company_id))` or it fails closed.
    pub async fn mark_processed(
        &self,
        pool: &PgPool,
        run_id: Uuid,
        total_gross: Decimal,
        total_deductions: Decimal,
        total_net: Decimal,
    ) -> Result<u64, sqlx::Error> {
        let done = company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE payroll.payroll_entries
                   SET status='processed'::payroll_status, total_gross=$2, total_deductions=$3, total_net=$4
                   WHERE id=$1 AND status='draft'::payroll_status"#,
            )
            .bind(run_id).bind(total_gross).bind(total_deductions).bind(total_net),
        )
        .await?;
        Ok(done.rows_affected())
    }

    /// Read a live run for GL posting. `Ok(None)` = not found in scope.
    ///
    /// ID-only: no company argument. Under HTTP the request-dedicated connection carries the scope.
    /// Driven by an EVENT, the caller must wrap this in `with_company_scope(Some(event.company_id))` —
    /// otherwise it fails closed.
    pub async fn find_for_posting(
        &self,
        pool: &PgPool,
        run_id: Uuid,
    ) -> Result<Option<RunPostingRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, status::text AS status, salary_expense_account_id, salary_payable_account_id,
                          total_gross, total_deductions, total_net, journal_id, accounting_post_id
                   FROM payroll.payroll_entries WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(run_id),
        )
        .await?;
        Ok(row.map(|r| RunPostingRow {
            company_id: r.get("company_id"), status: r.get("status"),
            salary_expense_account_id: r.get("salary_expense_account_id"),
            salary_payable_account_id: r.get("salary_payable_account_id"),
            total_gross: r.get("total_gross"), total_deductions: r.get("total_deductions"),
            total_net: r.get("total_net"), journal_id: r.get("journal_id"),
            accounting_post_id: r.get("accounting_post_id"),
        }))
    }

    /// Claim the `processed → posted` transition exactly once, recording the GL's echoed journal + post.
    /// Returns rows affected: 0 = a racing caller already posted it, so this one re-reads that journal.
    /// This gate is what makes a run post AT MOST once.
    ///
    /// A write outside any transaction; the caller wraps it in `with_company_scope(Some(company_id))`
    /// using the company it read off the run.
    pub async fn mark_posted(
        &self,
        pool: &PgPool,
        run_id: Uuid,
        posting_date: DateTime<Utc>,
        journal_id: Uuid,
        post_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE payroll.payroll_entries
                   SET status='posted'::payroll_status, posting_date=$2, journal_id=$3, accounting_post_id=$4
                   WHERE id=$1 AND status='processed'::payroll_status"#,
            )
            .bind(run_id).bind(posting_date).bind(journal_id).bind(post_id),
        )
        .await?;
        Ok(done.rows_affected())
    }

    /// Re-read the journal the winner recorded, after a lost `mark_posted` race. Caller supplies the
    /// company scope, as above.
    pub async fn fetch_journal_id(
        &self,
        pool: &PgPool,
        run_id: Uuid,
    ) -> Result<Uuid, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar("SELECT journal_id FROM payroll.payroll_entries WHERE id=$1")
                .bind(run_id),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(PayrollEntryRepository, PayrollEntry, soft_delete);
