//! Repository for SalaryComponent entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalaryComponent, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SalaryComponent;

/// Table name for SalaryComponent entities
pub const TABLE_NAME: &str = "payroll.salary_components";

/// Repository for SalaryComponent entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalaryComponentRepository(
    backbone_orm::GenericCrudRepository<SalaryComponent, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalaryComponentRepository {
    type Target = backbone_orm::GenericCrudRepository<SalaryComponent, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SalaryComponentRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SalaryComponentRepository, SalaryComponent, soft_delete);
