//! Repository for SalarySlipLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalarySlipLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SalarySlipLine;

/// Table name for SalarySlipLine entities
pub const TABLE_NAME: &str = "payroll.salary_slip_lines";

/// Repository for SalarySlipLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalarySlipLineRepository(
    backbone_orm::GenericCrudRepository<SalarySlipLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalarySlipLineRepository {
    type Target = backbone_orm::GenericCrudRepository<SalarySlipLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SalarySlipLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SalarySlipLineRepository, SalarySlipLine, soft_delete);
