//! Repository for SalarySlip entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalarySlip, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SalarySlip;

/// Table name for SalarySlip entities
pub const TABLE_NAME: &str = "payroll.salary_slips";

/// Repository for SalarySlip entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalarySlipRepository(
    backbone_orm::GenericCrudRepository<SalarySlip, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalarySlipRepository {
    type Target = backbone_orm::GenericCrudRepository<SalarySlip, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SalarySlipRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SalarySlipRepository, SalarySlip, soft_delete);
