//! Repository for SalaryStructure entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalaryStructure, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SalaryStructure;

/// Table name for SalaryStructure entities
pub const TABLE_NAME: &str = "payroll.salary_structures";

/// Repository for SalaryStructure entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalaryStructureRepository(
    backbone_orm::GenericCrudRepository<SalaryStructure, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalaryStructureRepository {
    type Target = backbone_orm::GenericCrudRepository<SalaryStructure, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SalaryStructureRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SalaryStructureRepository, SalaryStructure, soft_delete);
