//! Repository for SalaryStructure entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written SalaryStructure SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalaryStructure, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use crate::domain::entity::SalaryStructure;

/// Table name for SalaryStructure entities
pub const TABLE_NAME: &str = "payroll.salary_structures";

/// Repository for SalaryStructure entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalaryStructureRepository(
    backbone_orm::GenericCrudRepository<SalaryStructure, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalaryStructureRepository {
    type Target = backbone_orm::GenericCrudRepository<SalaryStructure, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SalaryStructureRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a structure definition writes. Mirrors the raw column shape, not the
/// `SalaryStructure` entity: the insert hard-codes `is_active = true`, so that column is not a
/// parameter.
pub struct NewStructureRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: &'a str,
}

/// Hand-written SalaryStructure SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl SalaryStructureRepository {
    /// Define a salary structure, active from the start.
    ///
    /// Takes the CALLER'S connection so the structure and its components commit as ONE unit. The caller
    /// has already bound the company on it (`bind_company_on`) so this passes the `app.company_id` WITH
    /// CHECK fence (ADR-0008) — don't re-bind here.
    pub async fn insert_structure(
        &self,
        conn: &mut sqlx::PgConnection,
        s: &NewStructureRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO payroll.salary_structures (id, company_id, name, is_active)
               VALUES ($1,$2,$3,true)"#,
        )
        .bind(s.id).bind(s.company_id).bind(s.name)
        .execute(conn)
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(SalaryStructureRepository, SalaryStructure, soft_delete);
