//! Validator for CompensationChange entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<CompensationChange>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::CompensationChange;

/// Validator type alias for CompensationChange entities.
pub type CompensationChangeValidator = EntityValidator<CompensationChange>;

/// Build a validator for CompensationChange with all schema-defined field rules.
pub fn compensation_change_validator() -> CompensationChangeValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("note", |e: &CompensationChange| e.note.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
