//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod payroll_entry_validator;
pub mod salary_slip_validator;
pub mod salary_slip_line_validator;
pub mod salary_structure_validator;
pub mod salary_component_validator;

pub use payroll_entry_validator::{PayrollEntryValidator, payroll_entry_validator};
pub use salary_slip_validator::{SalarySlipValidator, salary_slip_validator};
pub use salary_slip_line_validator::{SalarySlipLineValidator, salary_slip_line_validator};
pub use salary_structure_validator::{SalaryStructureValidator, salary_structure_validator};
pub use salary_component_validator::{SalaryComponentValidator, salary_component_validator};

// <<< CUSTOM
// END CUSTOM
