//! Validator for PayrollEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PayrollEntry>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::PayrollEntry;

/// Validator type alias for PayrollEntry entities.
pub type PayrollEntryValidator = EntityValidator<PayrollEntry>;

/// Build a validator for PayrollEntry with all schema-defined field rules.
pub fn payroll_entry_validator() -> PayrollEntryValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
