//! Validator for SalaryStructure entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SalaryStructure>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::SalaryStructure;

/// Validator type alias for SalaryStructure entities.
pub type SalaryStructureValidator = EntityValidator<SalaryStructure>;

/// Build a validator for SalaryStructure with all schema-defined field rules.
pub fn salary_structure_validator() -> SalaryStructureValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &SalaryStructure| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
