//! Validator for SalarySlipLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SalarySlipLine>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::SalarySlipLine;

/// Validator type alias for SalarySlipLine entities.
pub type SalarySlipLineValidator = EntityValidator<SalarySlipLine>;

/// Build a validator for SalarySlipLine with all schema-defined field rules.
pub fn salary_slip_line_validator() -> SalarySlipLineValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &SalarySlipLine| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
