//! Validator for SalaryComponent entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SalaryComponent>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::SalaryComponent;

/// Validator type alias for SalaryComponent entities.
pub type SalaryComponentValidator = EntityValidator<SalaryComponent>;

/// Build a validator for SalaryComponent with all schema-defined field rules.
pub fn salary_component_validator() -> SalaryComponentValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &SalaryComponent| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
