//! Validator for SalarySlip entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SalarySlip>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::SalarySlip;

/// Validator type alias for SalarySlip entities.
pub type SalarySlipValidator = EntityValidator<SalarySlip>;

/// Build a validator for SalarySlip with all schema-defined field rules.
pub fn salary_slip_validator() -> SalarySlipValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
