//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod payroll_entry_auth;
pub mod salary_slip_auth;
pub mod salary_slip_line_auth;
pub mod salary_structure_auth;
pub mod salary_component_auth;

pub use payroll_entry_auth::{PayrollEntryPolicy, PayrollEntryGuard, PayrollEntryServiceGuard};
pub use salary_slip_auth::{SalarySlipPolicy, SalarySlipGuard, SalarySlipServiceGuard};
pub use salary_slip_line_auth::{SalarySlipLinePolicy, SalarySlipLineGuard, SalarySlipLineServiceGuard};
pub use salary_structure_auth::{SalaryStructurePolicy, SalaryStructureGuard, SalaryStructureServiceGuard};
pub use salary_component_auth::{SalaryComponentPolicy, SalaryComponentGuard, SalaryComponentServiceGuard};

// <<< CUSTOM
// END CUSTOM
