//! Auth configuration for PayrollEntry handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PayrollEntry>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PayrollEntryService;
use crate::domain::entity::PayrollEntry;

/// Permission string constants for PayrollEntry operations.
pub mod permissions {
    pub const LIST:        &str = "payroll_entry:list";
    pub const READ:        &str = "payroll_entry:read";
    pub const CREATE:      &str = "payroll_entry:create";
    pub const UPDATE:      &str = "payroll_entry:update";
    pub const DELETE:      &str = "payroll_entry:delete";
    pub const RESTORE:     &str = "payroll_entry:restore";
    pub const TRASH:       &str = "payroll_entry:trash";
    pub const EMPTY_TRASH: &str = "payroll_entry:empty_trash";
    pub const BULK_CREATE: &str = "payroll_entry:bulk_create";
    pub const UPSERT:      &str = "payroll_entry:upsert";
}

/// Resource policy for PayrollEntry — maps CRUD actions to permission strings.
pub struct PayrollEntryPolicy;

#[async_trait]
impl ResourcePolicy<PayrollEntry> for PayrollEntryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PayrollEntry,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PayrollEntry handlers.
///
/// Wraps `PayrollEntryService` and checks `PayrollEntryPolicy` before delegating.
pub type PayrollEntryGuard = PermissionGuard<PayrollEntry>;

/// Service-integrated permission guard for PayrollEntry (for use in generated handlers).
pub type PayrollEntryServiceGuard = ServicePermissionGuard<PayrollEntry, PayrollEntryService, PayrollEntryPolicy>;

// <<< CUSTOM
// END CUSTOM
