//! Auth configuration for SalarySlip handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SalarySlip>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SalarySlipService;
use crate::domain::entity::SalarySlip;

/// Permission string constants for SalarySlip operations.
pub mod permissions {
    pub const LIST:        &str = "salary_slip:list";
    pub const READ:        &str = "salary_slip:read";
    pub const CREATE:      &str = "salary_slip:create";
    pub const UPDATE:      &str = "salary_slip:update";
    pub const DELETE:      &str = "salary_slip:delete";
    pub const RESTORE:     &str = "salary_slip:restore";
    pub const TRASH:       &str = "salary_slip:trash";
    pub const EMPTY_TRASH: &str = "salary_slip:empty_trash";
    pub const BULK_CREATE: &str = "salary_slip:bulk_create";
    pub const UPSERT:      &str = "salary_slip:upsert";
}

/// Resource policy for SalarySlip — maps CRUD actions to permission strings.
pub struct SalarySlipPolicy;

#[async_trait]
impl ResourcePolicy<SalarySlip> for SalarySlipPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SalarySlip,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SalarySlip handlers.
///
/// Wraps `SalarySlipService` and checks `SalarySlipPolicy` before delegating.
pub type SalarySlipGuard = PermissionGuard<SalarySlip>;

/// Service-integrated permission guard for SalarySlip (for use in generated handlers).
pub type SalarySlipServiceGuard = ServicePermissionGuard<SalarySlip, SalarySlipService, SalarySlipPolicy>;

// <<< CUSTOM
// END CUSTOM
