//! Auth configuration for SalaryComponent handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SalaryComponent>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SalaryComponentService;
use crate::domain::entity::SalaryComponent;

/// Permission string constants for SalaryComponent operations.
pub mod permissions {
    pub const LIST:        &str = "salary_component:list";
    pub const READ:        &str = "salary_component:read";
    pub const CREATE:      &str = "salary_component:create";
    pub const UPDATE:      &str = "salary_component:update";
    pub const DELETE:      &str = "salary_component:delete";
    pub const RESTORE:     &str = "salary_component:restore";
    pub const TRASH:       &str = "salary_component:trash";
    pub const EMPTY_TRASH: &str = "salary_component:empty_trash";
    pub const BULK_CREATE: &str = "salary_component:bulk_create";
    pub const UPSERT:      &str = "salary_component:upsert";
}

/// Resource policy for SalaryComponent — maps CRUD actions to permission strings.
pub struct SalaryComponentPolicy;

#[async_trait]
impl ResourcePolicy<SalaryComponent> for SalaryComponentPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SalaryComponent,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SalaryComponent handlers.
///
/// Wraps `SalaryComponentService` and checks `SalaryComponentPolicy` before delegating.
pub type SalaryComponentGuard = PermissionGuard<SalaryComponent>;

/// Service-integrated permission guard for SalaryComponent (for use in generated handlers).
pub type SalaryComponentServiceGuard = ServicePermissionGuard<SalaryComponent, SalaryComponentService, SalaryComponentPolicy>;

// <<< CUSTOM
// END CUSTOM
