//! Auth configuration for SalarySlipLine handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SalarySlipLine>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SalarySlipLineService;
use crate::domain::entity::SalarySlipLine;

/// Permission string constants for SalarySlipLine operations.
pub mod permissions {
    pub const LIST:        &str = "salary_slip_line:list";
    pub const READ:        &str = "salary_slip_line:read";
    pub const CREATE:      &str = "salary_slip_line:create";
    pub const UPDATE:      &str = "salary_slip_line:update";
    pub const DELETE:      &str = "salary_slip_line:delete";
    pub const RESTORE:     &str = "salary_slip_line:restore";
    pub const TRASH:       &str = "salary_slip_line:trash";
    pub const EMPTY_TRASH: &str = "salary_slip_line:empty_trash";
    pub const BULK_CREATE: &str = "salary_slip_line:bulk_create";
    pub const UPSERT:      &str = "salary_slip_line:upsert";
}

/// Resource policy for SalarySlipLine — maps CRUD actions to permission strings.
pub struct SalarySlipLinePolicy;

#[async_trait]
impl ResourcePolicy<SalarySlipLine> for SalarySlipLinePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SalarySlipLine,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SalarySlipLine handlers.
///
/// Wraps `SalarySlipLineService` and checks `SalarySlipLinePolicy` before delegating.
pub type SalarySlipLineGuard = PermissionGuard<SalarySlipLine>;

/// Service-integrated permission guard for SalarySlipLine (for use in generated handlers).
pub type SalarySlipLineServiceGuard = ServicePermissionGuard<SalarySlipLine, SalarySlipLineService, SalarySlipLinePolicy>;

// <<< CUSTOM
// END CUSTOM
