//! Auth configuration for SalaryStructure handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SalaryStructure>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SalaryStructureService;
use crate::domain::entity::SalaryStructure;

/// Permission string constants for SalaryStructure operations.
pub mod permissions {
    pub const LIST:        &str = "salary_structure:list";
    pub const READ:        &str = "salary_structure:read";
    pub const CREATE:      &str = "salary_structure:create";
    pub const UPDATE:      &str = "salary_structure:update";
    pub const DELETE:      &str = "salary_structure:delete";
    pub const RESTORE:     &str = "salary_structure:restore";
    pub const TRASH:       &str = "salary_structure:trash";
    pub const EMPTY_TRASH: &str = "salary_structure:empty_trash";
    pub const BULK_CREATE: &str = "salary_structure:bulk_create";
    pub const UPSERT:      &str = "salary_structure:upsert";
}

/// Resource policy for SalaryStructure — maps CRUD actions to permission strings.
pub struct SalaryStructurePolicy;

#[async_trait]
impl ResourcePolicy<SalaryStructure> for SalaryStructurePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SalaryStructure,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SalaryStructure handlers.
///
/// Wraps `SalaryStructureService` and checks `SalaryStructurePolicy` before delegating.
pub type SalaryStructureGuard = PermissionGuard<SalaryStructure>;

/// Service-integrated permission guard for SalaryStructure (for use in generated handlers).
pub type SalaryStructureServiceGuard = ServicePermissionGuard<SalaryStructure, SalaryStructureService, SalaryStructurePolicy>;

// <<< CUSTOM
// END CUSTOM
