//! CompensationChange API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the CompensationChange CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// COMPENSATIONCHANGE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for CompensationChange
pub struct CompensationChangeTestData;

impl TestDataGenerator for CompensationChangeTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "change_type": "hire",
            "new_amount": null,
            "effective_date": null,
            "reference_id": null,
            "note": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "change_type": "hire",
            "new_amount": null,
            "effective_date": null,
            "reference_id": null,
            "note": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// COMPENSATIONCHANGE API TEST
// ============================================================================

/// CompensationChange API test suite
pub struct CompensationChangeApiTest {
    inner: GenericCrudTest<CompensationChangeTestData>,
}

impl CompensationChangeApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/compensation_changes", "CompensationChange");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CompensationChangeTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CompensationChangeApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_compensation_change_crud() {
        let mut test = CompensationChangeApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add CompensationChange specific tests here
// <<< CUSTOM TESTS END >>>
