//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod payroll_entry_api_test;
pub mod salary_slip_api_test;
pub mod salary_slip_line_api_test;
pub mod salary_structure_api_test;
pub mod salary_component_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use payroll_entry_api_test::*;
pub use salary_slip_api_test::*;
pub use salary_slip_line_api_test::*;
pub use salary_structure_api_test::*;
pub use salary_component_api_test::*;
