//! SalarySlipLine API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SalarySlipLine CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SALARYSLIPLINE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SalarySlipLine
pub struct SalarySlipLineTestData;

impl TestDataGenerator for SalarySlipLineTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "salary_slip_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "component_type": "earning",
            "is_statutory": false,
            "amount": 0,
            "gl_account_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "salary_slip_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "component_type": "earning",
            "is_statutory": false,
            "amount": 0,
            "gl_account_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/salary_slips", &super::salary_slip_api_test::SalarySlipTestData).await {
            deps.push(("salary_slip_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SALARYSLIPLINE API TEST
// ============================================================================

/// SalarySlipLine API test suite
pub struct SalarySlipLineApiTest {
    inner: GenericCrudTest<SalarySlipLineTestData>,
}

impl SalarySlipLineApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/salary_slip_lines", "SalarySlipLine");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SalarySlipLineTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SalarySlipLineApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_salary_slip_line_crud() {
        let mut test = SalarySlipLineApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SalarySlipLine specific tests here
// <<< CUSTOM TESTS END >>>
