//! SalarySlip API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SalarySlip CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SALARYSLIP TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SalarySlip
pub struct SalarySlipTestData;

impl TestDataGenerator for SalarySlipTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "payroll_entry_id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "structure_id": null,
            "working_days": 0,
            "unpaid_days": 0,
            "gross_pay": 0,
            "total_deductions": 0,
            "net_pay": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "payroll_entry_id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "structure_id": null,
            "working_days": 0,
            "unpaid_days": 0,
            "gross_pay": 0,
            "total_deductions": 0,
            "net_pay": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/payroll_entries", &super::payroll_entry_api_test::PayrollEntryTestData).await {
            deps.push(("payroll_entry_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SALARYSLIP API TEST
// ============================================================================

/// SalarySlip API test suite
pub struct SalarySlipApiTest {
    inner: GenericCrudTest<SalarySlipTestData>,
}

impl SalarySlipApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/salary_slips", "SalarySlip");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SalarySlipTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SalarySlipApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_salary_slip_crud() {
        let mut test = SalarySlipApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SalarySlip specific tests here
// <<< CUSTOM TESTS END >>>
