//! SalaryComponent API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SalaryComponent CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SALARYCOMPONENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SalaryComponent
pub struct SalaryComponentTestData;

impl TestDataGenerator for SalaryComponentTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "structure_id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "component_type": "earning",
            "amount": 0,
            "gl_account_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "structure_id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "component_type": "earning",
            "amount": 0,
            "gl_account_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/salary_structures", &super::salary_structure_api_test::SalaryStructureTestData).await {
            deps.push(("structure_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SALARYCOMPONENT API TEST
// ============================================================================

/// SalaryComponent API test suite
pub struct SalaryComponentApiTest {
    inner: GenericCrudTest<SalaryComponentTestData>,
}

impl SalaryComponentApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/salary_components", "SalaryComponent");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SalaryComponentTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SalaryComponentApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_salary_component_crud() {
        let mut test = SalaryComponentApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SalaryComponent specific tests here
// <<< CUSTOM TESTS END >>>
