//! Payroll Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Payroll exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use payroll::exports::{PayrollEntryDto, PayrollQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `PayrollEntryDto` - Data transfer object for PayrollEntry
/// - `PayrollEntrySummary` - Summary view of PayrollEntry
/// - `PayrollEntryId` - Type-safe ID wrapper
/// - `SalarySlipDto` - Data transfer object for SalarySlip
/// - `SalarySlipSummary` - Summary view of SalarySlip
/// - `SalarySlipId` - Type-safe ID wrapper
/// - `SalarySlipLineDto` - Data transfer object for SalarySlipLine
/// - `SalarySlipLineSummary` - Summary view of SalarySlipLine
/// - `SalarySlipLineId` - Type-safe ID wrapper
/// - `SalaryStructureDto` - Data transfer object for SalaryStructure
/// - `SalaryStructureSummary` - Summary view of SalaryStructure
/// - `SalaryStructureId` - Type-safe ID wrapper
/// - `SalaryComponentDto` - Data transfer object for SalaryComponent
/// - `SalaryComponentSummary` - Summary view of SalaryComponent
/// - `SalaryComponentId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `PayrollQueryService` - Read-only queries
///
/// ## Public Events
/// - `PayrollEntryCreatedEvent` - Published when PayrollEntry is created
/// - `PayrollEntryUpdatedEvent` - Published when PayrollEntry is updated
/// - `PayrollEntryDeletedEvent` - Published when PayrollEntry is deleted
/// - `SalarySlipCreatedEvent` - Published when SalarySlip is created
/// - `SalarySlipUpdatedEvent` - Published when SalarySlip is updated
/// - `SalarySlipDeletedEvent` - Published when SalarySlip is deleted
/// - `SalarySlipLineCreatedEvent` - Published when SalarySlipLine is created
/// - `SalarySlipLineUpdatedEvent` - Published when SalarySlipLine is updated
/// - `SalarySlipLineDeletedEvent` - Published when SalarySlipLine is deleted
/// - `SalaryStructureCreatedEvent` - Published when SalaryStructure is created
/// - `SalaryStructureUpdatedEvent` - Published when SalaryStructure is updated
/// - `SalaryStructureDeletedEvent` - Published when SalaryStructure is deleted
/// - `SalaryComponentCreatedEvent` - Published when SalaryComponent is created
/// - `SalaryComponentUpdatedEvent` - Published when SalaryComponent is updated
/// - `SalaryComponentDeletedEvent` - Published when SalaryComponent is deleted
pub struct ExportSummary;
