//! Public services for Payroll module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Payroll module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait PayrollQueryService: Send + Sync {
    /// Get PayrollEntry by ID
    async fn get_payroll_entry(&self, id: PayrollEntryId) -> Result<Option<PayrollEntryDto>>;

    /// Get PayrollEntry summary by ID
    async fn get_payroll_entry_summary(&self, id: PayrollEntryId) -> Result<Option<PayrollEntrySummary>>;

    /// Check if PayrollEntry exists
    async fn payroll_entry_exists(&self, id: PayrollEntryId) -> Result<bool>;

    /// Get SalarySlip by ID
    async fn get_salary_slip(&self, id: SalarySlipId) -> Result<Option<SalarySlipDto>>;

    /// Get SalarySlip summary by ID
    async fn get_salary_slip_summary(&self, id: SalarySlipId) -> Result<Option<SalarySlipSummary>>;

    /// Check if SalarySlip exists
    async fn salary_slip_exists(&self, id: SalarySlipId) -> Result<bool>;

    /// Get SalarySlipLine by ID
    async fn get_salary_slip_line(&self, id: SalarySlipLineId) -> Result<Option<SalarySlipLineDto>>;

    /// Get SalarySlipLine summary by ID
    async fn get_salary_slip_line_summary(&self, id: SalarySlipLineId) -> Result<Option<SalarySlipLineSummary>>;

    /// Check if SalarySlipLine exists
    async fn salary_slip_line_exists(&self, id: SalarySlipLineId) -> Result<bool>;

    /// Get SalaryStructure by ID
    async fn get_salary_structure(&self, id: SalaryStructureId) -> Result<Option<SalaryStructureDto>>;

    /// Get SalaryStructure summary by ID
    async fn get_salary_structure_summary(&self, id: SalaryStructureId) -> Result<Option<SalaryStructureSummary>>;

    /// Check if SalaryStructure exists
    async fn salary_structure_exists(&self, id: SalaryStructureId) -> Result<bool>;

    /// Get SalaryComponent by ID
    async fn get_salary_component(&self, id: SalaryComponentId) -> Result<Option<SalaryComponentDto>>;

    /// Get SalaryComponent summary by ID
    async fn get_salary_component_summary(&self, id: SalaryComponentId) -> Result<Option<SalaryComponentSummary>>;

    /// Check if SalaryComponent exists
    async fn salary_component_exists(&self, id: SalaryComponentId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of PayrollQueryService
pub struct PayrollQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> PayrollQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
