//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod payroll_entry_usecases;
pub mod salary_slip_usecases;
pub mod salary_slip_line_usecases;
pub mod salary_structure_usecases;
pub mod salary_component_usecases;

pub use payroll_entry_usecases::{
    CreatePayrollEntryUseCase, UpdatePayrollEntryUseCase, GetPayrollEntryUseCase,
    DeletePayrollEntryUseCase, ListPayrollEntryUseCase,
};
pub use salary_slip_usecases::{
    CreateSalarySlipUseCase, UpdateSalarySlipUseCase, GetSalarySlipUseCase,
    DeleteSalarySlipUseCase, ListSalarySlipUseCase,
};
pub use salary_slip_line_usecases::{
    CreateSalarySlipLineUseCase, UpdateSalarySlipLineUseCase, GetSalarySlipLineUseCase,
    DeleteSalarySlipLineUseCase, ListSalarySlipLineUseCase,
};
pub use salary_structure_usecases::{
    CreateSalaryStructureUseCase, UpdateSalaryStructureUseCase, GetSalaryStructureUseCase,
    DeleteSalaryStructureUseCase, ListSalaryStructureUseCase,
};
pub use salary_component_usecases::{
    CreateSalaryComponentUseCase, UpdateSalaryComponentUseCase, GetSalaryComponentUseCase,
    DeleteSalaryComponentUseCase, ListSalaryComponentUseCase,
};

// <<< CUSTOM
// END CUSTOM
