//! Use case type aliases for PayrollEntry aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePayrollEntryDto, UpdatePayrollEntryDto};
use crate::application::service::PayrollEntryService;
use crate::domain::entity::PayrollEntry;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePayrollEntryUseCase = CreateUseCase<PayrollEntry, CreatePayrollEntryDto, PayrollEntryService>;
pub type UpdatePayrollEntryUseCase = UpdateUseCase<PayrollEntry, UpdatePayrollEntryDto, PayrollEntryService>;
pub type GetPayrollEntryUseCase    = GetUseCase<PayrollEntry, PayrollEntryService>;
pub type DeletePayrollEntryUseCase = DeleteUseCase<PayrollEntry, PayrollEntryService>;
pub type ListPayrollEntryUseCase   = ListUseCase<PayrollEntry, PayrollEntryService>;

// <<< CUSTOM
// END CUSTOM
