//! Use case type aliases for SalaryStructure aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSalaryStructureDto, UpdateSalaryStructureDto};
use crate::application::service::SalaryStructureService;
use crate::domain::entity::SalaryStructure;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSalaryStructureUseCase = CreateUseCase<SalaryStructure, CreateSalaryStructureDto, SalaryStructureService>;
pub type UpdateSalaryStructureUseCase = UpdateUseCase<SalaryStructure, UpdateSalaryStructureDto, SalaryStructureService>;
pub type GetSalaryStructureUseCase    = GetUseCase<SalaryStructure, SalaryStructureService>;
pub type DeleteSalaryStructureUseCase = DeleteUseCase<SalaryStructure, SalaryStructureService>;
pub type ListSalaryStructureUseCase   = ListUseCase<SalaryStructure, SalaryStructureService>;

// <<< CUSTOM
// END CUSTOM
