//! Use case type aliases for SalarySlipLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSalarySlipLineDto, UpdateSalarySlipLineDto};
use crate::application::service::SalarySlipLineService;
use crate::domain::entity::SalarySlipLine;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSalarySlipLineUseCase = CreateUseCase<SalarySlipLine, CreateSalarySlipLineDto, SalarySlipLineService>;
pub type UpdateSalarySlipLineUseCase = UpdateUseCase<SalarySlipLine, UpdateSalarySlipLineDto, SalarySlipLineService>;
pub type GetSalarySlipLineUseCase    = GetUseCase<SalarySlipLine, SalarySlipLineService>;
pub type DeleteSalarySlipLineUseCase = DeleteUseCase<SalarySlipLine, SalarySlipLineService>;
pub type ListSalarySlipLineUseCase   = ListUseCase<SalarySlipLine, SalarySlipLineService>;

// <<< CUSTOM
// END CUSTOM
