//! Use case type aliases for SalaryComponent aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSalaryComponentDto, UpdateSalaryComponentDto};
use crate::application::service::SalaryComponentService;
use crate::domain::entity::SalaryComponent;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSalaryComponentUseCase = CreateUseCase<SalaryComponent, CreateSalaryComponentDto, SalaryComponentService>;
pub type UpdateSalaryComponentUseCase = UpdateUseCase<SalaryComponent, UpdateSalaryComponentDto, SalaryComponentService>;
pub type GetSalaryComponentUseCase    = GetUseCase<SalaryComponent, SalaryComponentService>;
pub type DeleteSalaryComponentUseCase = DeleteUseCase<SalaryComponent, SalaryComponentService>;
pub type ListSalaryComponentUseCase   = ListUseCase<SalaryComponent, SalaryComponentService>;

// <<< CUSTOM
// END CUSTOM
