//! Use case type aliases for SalarySlip aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSalarySlipDto, UpdateSalarySlipDto};
use crate::application::service::SalarySlipService;
use crate::domain::entity::SalarySlip;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSalarySlipUseCase = CreateUseCase<SalarySlip, CreateSalarySlipDto, SalarySlipService>;
pub type UpdateSalarySlipUseCase = UpdateUseCase<SalarySlip, UpdateSalarySlipDto, SalarySlipService>;
pub type GetSalarySlipUseCase    = GetUseCase<SalarySlip, SalarySlipService>;
pub type DeleteSalarySlipUseCase = DeleteUseCase<SalarySlip, SalarySlipService>;
pub type ListSalarySlipUseCase   = ListUseCase<SalarySlip, SalarySlipService>;

// <<< CUSTOM
// END CUSTOM
