//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod compensation_change_handler;
pub mod payroll_entry_handler;
pub mod salary_slip_handler;
pub mod salary_slip_line_handler;
pub mod salary_structure_handler;
pub mod salary_component_handler;

// <<< CUSTOM
// Guarded composition (user-owned file): validated run verbs + computed slips + safe reads, no
// generic run/slip/slip-line mutation.
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use compensation_change_handler::{create_compensation_change_routes, create_compensation_change_read_routes, create_compensation_change_write_routes};
pub use payroll_entry_handler::{create_payroll_entry_routes, create_payroll_entry_read_routes, create_payroll_entry_write_routes};
pub use salary_slip_handler::{create_salary_slip_routes, create_salary_slip_read_routes, create_salary_slip_write_routes};
pub use salary_slip_line_handler::{create_salary_slip_line_routes, create_salary_slip_line_read_routes, create_salary_slip_line_write_routes};
pub use salary_structure_handler::{create_salary_structure_routes, create_salary_structure_read_routes, create_salary_structure_write_routes};
pub use salary_component_handler::{create_salary_component_routes, create_salary_component_read_routes, create_salary_component_write_routes};
// <<< CUSTOM
pub use guarded_routes::create_guarded_payroll_routes;
// END CUSTOM
